### ISSUE TITLE
Configure complex resources

### ISSUE THREAD

**Issue by ghost** [codecutout/JsonApiSerializer#110]
Hi! 
Is it possible to configure it to not add specific list subresources in Include object but keep them in attributes? 
I want the default behaviour of this library **but for some cases I want lists to be part of the main resource**

Thank you

**Comment by ghost** [comment]
Example:

```
"data": [
    {
      "id": "1",
      "type": "contact",
      "attributes": {
           "name":"John",
           "phones": 
           [
              {
                "phoneNumber": "0272276"
              },
               {
                "phoneNumber": "3333333"
              }
           ]
      }}]
```

**Comment by alex-davies** [comment]
@ClaudiuSocaci you can do this by ensure your child object does _not_ have an `Id` attribute. If it has an `Id` attribute it will assume it is a resource object and add it to the relationship and includes, otherwise it will assume its an attribute and output it inline

For your example if you have the following classes
```csharp
public class Contact
{
    public string Id { get; set; }

    public string Type => "contact";

    public string Name { get; set; }

    public Phone[] Phones { get; set; }
}

public class Phone
{
    public string PhoneNumber { get; set; }
}
```

Then you can get your output by doing
```csharp
var json = JsonConvert.SerializeObject(new Contact[] 
{
    new Contact
    {
        Id = "1",
        Name = "John",
        Phones = new Phone[]
        {
            new Phone() { PhoneNumber =  "0272276" },
            new Phone() { PhoneNumber =  "3333333" }
        }
    }
}, new JsonApiSerializerSettings() { Formatting = Formatting.Indented });
```

**Comment by ghost** [comment]
Thanks @alex-davies . Is there a way to include Phones even if you have the id in there? 
I guess not.

**Comment by ghost** [comment]
@alex-davies thanks for help. I mainly wanted to understand it a bit better so I will close this issue.
