### ISSUE TITLE
Dynamic attribute serialization & deserialization

### ISSUE THREAD

**Issue by kjanos0502** [codecutout/JsonApiSerializer#120]
Hi,

In my model class I'm expecting attributes in a dynamic manner, some of them are known at compile time, some of them are not.

    public class ClassA
    {
        private Dictionary<string, object> attributes;
    
        public string AttributeA { get => attributes["AttributeA"]; set => attributes["AttributeA"] = value; }
        public string AttributeB { get => attributes["AttributeB"]; set => attributes["AttributeB"] = value; }
    }

Is there a way I could serialize (collecting the attributes from the dictionary) and deserialize (filling up the dictionary) properly even if the dictionary contains an entry with key e.g. AttributeC at runtime?

The workaround I tried was overriding ResourceObjectConverter's WriteJson in a way that I create a new class at runtime which has all the properties that are contained in the original dictionary. This works fine as I can pass the instance of the dynamically created class to the base's WriteJson. It's probably not cheap, though.

However, I'm unable to read it back as I can't seem to find a way to peak the JsonReader in ReadJson, check what extra attributes are present, let base.ReadJson do the work and populate the dictionary with the extra entries.

**Comment by alex-davies** [comment]
If you have some control over the contract you could have an attribute of type `Dictionary<string,string>`. This does mean the dynamic attributes would be nested down one layer

**Comment by kjanos0502** [comment]
Yes, I wanted to avoid nesting them one level below. I ended up not deserializing the info at all and took a different approach.
