### ISSUE TITLE
How to return relationship without Include.

### ISSUE THREAD

**Issue by klepeis** [codecutout/JsonApiSerializer#124]
I have an API where I would like to return and object with its relationships but not with the include.  So for example

/contact/1 

Would return...

`
"data": {
        "id": "1",
        "type": "contact-info",
        "attributes": {
            "first-name": "fName",
            "last-name": "lName",
            "birth-date": "0001-01-01T00:00:00",
        },
        "relationships": {
            "emails": {
                "data": [
                    {
                        "id": "4",
                        "type": "email-address"
                    },
                    {
                        "id": "5",
                        "type": "email-address"
                    }
                ]
            }
        }
    }
}
`

And
/contact/1/emails  would return 

`
"data": {
        "id": "1",
        "type": "contact-info",
        "attributes": {
            "first-name": "fName",
            "last-name": "lName",
            "birth-date": "0001-01-01T00:00:00",
        },
        "relationships": {
            "emails": {
                "data": [
                    {
                        "id": "4",
                        "type": "email-address"
                    },
                    {
                        "id": "5",
                        "type": "email-address"
                    }
                ]
            }
        }
    },
   "included": [
      {
         "id": "4",
         "type": "email-address",
         "attributes": {
            "email": "some@email.com"
         }
      },
       {
         "id": "5",
         "type": "email-address",
         "attributes": {
            "email": "some@email.com"
         }
      }
   ]
}
`

Is there an easy way to accomplish this or is it a matter of my just populating an object with "id and type" and that is all for the first call?

**Comment by alex-davies** [comment]
If you don't want an object to return in the `include` then you can only have an id and type property then it will not bother adding an item into the include

In your case it would probably be done by having separate models you return from the endpoint. Which would also make your response objects more accurately model what your API is expected to return
