### ISSUE TITLE
Deserialization of attribute not working if complex type

### ISSUE THREAD

**Issue by rcabreu** [codecutout/JsonApiSerializer#127]
Sample JSON: https://docs.withpersona.com/docs/webhooks

The atrribute "payload" is a complex object. I've seen that the best case is to NOT include this object in the attributes object, and instead have a reference for it in the "relationships" object, and the actual object in the "included" array. 

JsonApiSerializer is not able to deserialize this "payload" object. According to the specs (https://jsonapi.org/format/#document-resource-object-attributes), "complex data structures are allowed" as part of the attributes.

Please fix! I've to resort to a workaround in order to get a deserialized payload.

**Comment by jfrancisco-neto** [comment]
Complex data structs are allowed. See DATA STRUCTS. In your case is a entire object with type and id. So it should be sent in a relationship since JsonApi format doesn't allow id's in it's attributes.

See the text: 

> Although has-one foreign keys (e.g. author_id) are often stored internally alongside other information to be represented in a resource object, these keys SHOULD NOT appear as attributes.

**Comment by rcabreu** [comment]
Thanks! Unfortunately, withpersona.com sends in this bizarre JSON, after some internal design trade-offs they've made.

We'll stick to our workaround to work with them. Thank you, CronosTs.
