### ISSUE TITLE
Usage vs normal WebAPI

### ISSUE THREAD

**Issue by glinkot** [codecutout/JsonApiSerializer#20]
Hi,

This is really a question not an issue.  I've kicked off my API explorations with .NET Core and the type of approach here (https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/existing-db).  This project looks perfectly aligned to that, with the same structure for defining the objects etc.

I was wondering when this project is recommended versus using the deserialisation provided by WebAPI when you tell it a particular object is in the request body and should be deserialised from there.

Many thanks!

**Comment by alex-davies** [comment]
This project is recommended if you need to either produce or consume an API that is using the specific json format from http://jsonapi.org/. 

The confusingly named json:api is not the same as a web api that returns json. json:api specifies how data and relationships should be modelled within the json request and response objects.

The json:api format is good if you have lots of interrelated objects that include circular dependencies or lots of many-to-one relationships. However if you models can easily be represented in standard json it would probably be simpler not to add the additional complexities of json:api.

**Comment by glinkot** [comment]
Many thanks, that's a big help :)
