### ISSUE TITLE
Issue when serializing EF select result

### ISSUE THREAD

**Issue by neguso** [codecutout/JsonApiSerializer#21]
Serializing the following:
```csharp
new DocumentRoot<IEnumerable<Service>>
{
  Data = records
};
```
will produce wrong JSON output if `records` is an `IEnumerable<Service>` result from an `Select(...)` method call:

```json
{
    "data": [
        {
            "type": "Service",
            "id": "ff3e06c0-7bdc-9846-bd33-42421f8b289f",
            "attributes": {
                "name": "Service 1",
                "date": "2017-01-01T00:00:00",
                "favorite": true
            }
        }
    ],
    "included": [
        {
            "type": "Service",
            "id": "ff3e06c0-7bdc-9846-bd33-42421f8b289f",
            "attributes": {
                "name": "Service 1",
                "date": "2017-01-01T00:00:00",
                "favorite": true
            }
        }
    ]
}
```
Note the unnecessary `included` property.
The serialization works well if I convert `records` to a `List<Service>`:
```csharp
new DocumentRoot<IEnumerable<Service>>
{
  Data = records.ToList()
};
```

**Comment by alex-davies** [comment]
Can you confirm which version you are on? 

I cant reproduce the issue on the 0.9.17. The last update included a fix which changed how IEnumerables were handled that may resolve this issue.

**Comment by neguso** [comment]
I'm using 0.9.16 from nuget.org. Will check the new version when available.
