### ISSUE TITLE
Dynamically create Relationship Items

### ISSUE THREAD

**Issue by Jetski5822** [codecutout/JsonApiSerializer#22]
At the moment if I want a relationship I need to do this..

> public Relationship<List<Author>> Authors { get; set; }

And this gives me an author inside of the Relationships of the resource object. However, I dont know Authors until run time. I want something more like....

> public Relationship<IDictionary<string, List<ApiRelationItem>>> Relationships { get; set; }

Now I could have anything added and all would be good. Any ideas how I could do this?

**Comment by alex-davies** [comment]
Handling untyped values will be an issue. Deserializer uses the classes defined types to know how to deserialize an object. You might be able to set it up if you knew all relationships will be a list of the same type i.e. 'IDictionary<string,List<Person>>`

Probably the easiest way to solve your issue is to create properties for all the relationships you need then check the properties for null to determine which data you have.

**Comment by Jetski5822** [comment]
I dont know the relationships at compile time, as this is for a CMS is a runtime concern.

So I have a type, called ApiRelationshipItem, its the same type for all relationships, however, One relationship might be different to another, i.e an author vs comment, however they are both ApiRelationshipItem's, but, I dont know about Author or Comment at compile time, I only find out about them at run time.

**Comment by alex-davies** [comment]
You may not know which relationships will be present, but do you know which ones you will be reading? You must know at compile time if you will want to process the 'Author' field or not, You don't need to include all the fields that will be present, just the ones you want to read.

If you truely need to read them dynamically, you are in for a long difficult battle. This library is driven by the types defined, without knowing what type an object should be there is little this library can do to help you.

On saying that it is possible to create a property on an object like
```csharp
public Dictionary<string, Relationship<JToken>> Relationships { get; set; }
```
This will deserialize, but be aware the JToken will only have an id and type property, you will then need to go into the `DocumentRoot.Included` and resolve it to the actual `JObject` data, then that object may in turn have other relationships to be resolved. Going down this route means you will have to manage the relationship linking yourself, which is the difficult part of json:api deserialization, and normally why you would use a library in the first place.

**Comment by alex-davies** [comment]
While testing that the Relationships property worked, i noticed a bug in that it was not populating the included in the document, have fixed that, so should you want to go down the path of resolving links the data will be available in the `included' property.
