### ISSUE TITLE
Expected to find string at data[0].id, The value of 'id' MUST be a string

### ISSUE THREAD

**Issue by wilhsms** [codecutout/JsonApiSerializer#36]
Hello,
I'm getting a json where the data.id is integer, by what I see in the ReaderUtil.ReadAheadToIdentifyObject class it is mandatory that it be string. Is there any way to change this behavior?

**Comment by alex-davies** [comment]
json:api spec (http://jsonapi.org/format/#document-resource-object-identification) explicitly states that 
> The values of the id and type members MUST be strings.

No easy way to change this behaviour, but if you are getting id's as integers then the service you are consuming is not json:api

**Comment by wilhsms** [comment]
Really Alex, you're right.
I already questioned the third party supplier about this because it caused me confusion.

Thanks
