### ISSUE TITLE
Check if "type" value matches type before deserializing

### ISSUE THREAD

**Issue by cmeeren** [codecutout/JsonApiSerializer#42]
I have a sign-in endpoint that should accept two different resources: A `User` resource with username and password, and a `ConfirmationCode` resource containing an SMS confirmation code.

For example, it should accept both

```json
{
  "data": {
    "type": "user",
    "attributes": {
      "username": "someUser",
      "password": "somePwd"
    }
  }
}
```

and

```json
{
  "data": {
    "type": "confirmation-code",
    "id": "6081f88f-8a7d-44ef-902b-76fc66461808",
    "attributes": {
      "code": "1234"
    }
  }
}
```

I would expect that when I try to deserialize the first json above to a `ConfirmationCode` object, it should fail since the JSON API type does not match. What actually happens is that I simply get an empty `User` object.

Would it be possible to check the "type" parameter before deserializing, and failing in some way (e.g. throwing an exception) if the type does not match?

**Comment by alex-davies** [comment]
The behaviour of deserializing as best effort matches what json.net does, we don't error if we can't match properties we just do what we can. 

For the most part we don't actually do any matching types. On deserialization we treat them like another property, on serialization we only default generate them so we are spec compliant.

If it were to be added it would have to be as a setting that is defaulted to not check, id rather avoid having too many obscure features

In your particular case you could easily do a post-serialization check on 
```csharp
if(data.type != "confirmation-code")
    throw new Exception();
```

**Comment by cmeeren** [comment]
Thanks. I didn't think of checking the `Type` property. However, that requires (1) adding it to every type I want to check (as opposed to auto-generating it), and (2) having the property name as a string in multiple locations, so it's not ideal.

I agree that a setting that defaulted to not check this would be the ideal solution.

**Comment by alex-davies** [comment]
You could also do this with a custom ResourceObjectConverter.

Something like
```csharp
    public class TypeCheckingResourceObjectConverter : ResourceObjectConverter
    {
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            var obj = base.ReadJson(reader, objectType, existingValue, serializer);

            //get the result's Type field. You would need to make sure you define a type field for all your resource classes
            JsonObjectContract contract = (JsonObjectContract)serializer.ContractResolver.ResolveContract(objectType);
            var actualTypeName = contract.Properties.GetClosestMatchProperty("type").ValueProvider.GetValue(obj) as string;
            var expectedTypeName = this.GenerateDefaultTypeName(objectType);

            if (actualTypeName != null && expectedTypeName != actualTypeName)
                throw new Exception($"Unexpected type field, was expecting {expectedTypeName} but found {actualTypeName});

            return obj;
        }

        protected override string GenerateDefaultTypeName(Type type)
        {
            //TODO generate your preferred typenames here
            return base.GenerateDefaultTypeName(type);
        }
    }
```

you can pass an instance of `TypeCheckingResourceObjectConverter ` when creating the `JsonApiSerializerSettings` so it uses this for handling resource objects. 

I haven't actually tested the code, but should run on every resource object deserialization and can check the type names. Can even use it to custom generate type names (I believe you wanted them kebab case)

**Comment by cmeeren** [comment]
Thanks! Sounds perfect.

**Comment by cmeeren** [comment]
Doesn't seem to work. After calling `base.ReadJson`, the `Type` field of the object (as inspected in the debugger) has the default value even if the request specifies a different type.

**Comment by cmeeren** [comment]
Hold on, the error may be because I made the `Type` property get-only. Will test again when I have the time.

**Comment by cmeeren** [comment]
Hi again, just want to say that we moved away from JsonApiSerializer, and I won't be able to prioritize getting to the bottom of this.

**Comment by alex-davies** [comment]
Sorry to hear the library didn’t quite fit you your requirements. Out of curiosity have you moved to a different Json:api library?

**Comment by cmeeren** [comment]
We tried JsonApiFramework both before and after JsonApiSerializer, but in the end we found that a custom-written F#-centric framework would be the best choice.
