### ISSUE TITLE
How to map a relationship to the id property

### ISSUE THREAD

**Issue by opcodewriter** [codecutout/JsonApiSerializer#5]
Imagine a simple relationship where a `Foo` has a `Boo`:

```
 "data": [
        {
            "id": "1",
            "type": "foos",
            "relationships": {
                  "bar" :  {
                        data: {
                          "type": "bars",
                           "id": "1"
                       }
               }
            }
       }
```

What I'd like is to be able to deserialize Foo's "bar" relationship to the id, not to the full object.
See the comment for the `Bar` property below:

```
class Foo
{
         public int Id { get; set; }
         public Bar Bar { get; set; }    // instead, I would like to have this: public int BarId { get; set; }
}

class Bar 
{
          public int Id { get; set; }
}
```

How can I do this?

**Comment by alex-davies** [comment]
You can still have `public Bar Bar { get; set; }` but if the only data present in `Bar` is the id, type and meta (i.e. everything that we can output in the relationship) then it wont bother making an included item. Your example should just work.

See https://github.com/codecutout/JsonApiSerializer/blob/issues/5-how-to-map-a-relationship-to-the-id-property/tests/JsonApiSerializer.Test/SerializationTests/SerializationEmptyIncludedTests.cs

**Comment by opcodewriter** [comment]
Maybe I misunderstand your answer, I'm referring to deserialization not serialization.
Let me give you the big picture, I think that will help.
I have a case of recursive reference like this:

```
class Foo
{
         public int Id { get; set; }
         public Bar Bar { get; set; }
}

class Bar 
{
          public int Id { get; set; }
          public Foo Foo { get; set; }
}
````

That's why I was I thinking if it would be possible to have `public int BarId { get; set; }` in `Foo` and the library automagically figure out how to map a relationship to `Foo`'s `BarId` property.

On the other hand, in the meantime, I realized that the problem might actually be in the JSON API coming from backend. Recursive references in responses doesn't make sense.
What do you think?
I googled a bit and it seems that recursive referencing in JSON API is something others have stumbled upon. Some say it's bad design, some say it's fine and have workarounds in code.

**Comment by alex-davies** [comment]
Ah, sorry i misunderstood you original question.

It should handle circular references fine. I can deserialize
```js
{  
   "data":{  
      "type":"foo",
      "id":"1",
      "relationships":{  
         "bar":{  
            "data":{  
               "id":"1",
               "type":"bar"
            }
         }
      }
   },
   "included":[  
      {  
         "type":"bar",
         "id":"1",
         "relationships":{  
            "foo":{  
               "data":{  
                  "id":"1",
                  "type":"foo"
               }
            }
         }
      }
   ]
}
```
The output will be a `Foo` that references a `Bar`, and the `Bar` will references back to the original `Foo` instance.

Do you have a json string that demonstrates the issue you are having?

**Comment by alex-davies** [comment]
Alternatively you could make a something like

```csharp
public class Foo
{
    public string Id { get; set; }
    public BarReference Bar { get; set; }  
}
public class BarReference
{
    public string Id { get; set; }

    public string Type { get; set; } = "bar";
}
```
so it will only deserialize the Id of `Bar` and no other properties, you can then do what you want with the id.
