### ISSUE TITLE
Configure include options

### ISSUE THREAD

**Issue by erikpaperik** [codecutout/JsonApiSerializer#51]
Hi,

I'm currently searching for a possibility  to specify which related resources should be serialized as `included` resources in an serialized result.

E.g.: We have an `Article` with an one-to-one relationship to a `Person`
When receiving the request ` /articles/1?include=author` we want to return:
```json
{
  "data":{
    "type": "article",
    "id": "1",
    "relationships": {
      "author": {
         "data": { 
           "type": "people", 
           "id": "99" }
      }
    }
  },
  "included": [{
    "type": "people",
    "id": "99",
    "attributes": {
      "first-name": "Patrick",
      "last-name": "Gebhardt",
    }
  }]
}
```
On the other hand when receiving ` /articles/1` our response should look like
```json
{
  "data":{
    "type": "article",
    "id": "1",
    "relationships": {
      "author": {
         "data": { 
           "type": "people", 
           "id": "9" }
      }
    }
  }
}
```

From the code in `ResourceObjectConverter` listed below it looks like a resource is always included if there are properties w/ data (excluding several fields).

https://github.com/codecutout/JsonApiSerializer/blob/73943cac775b977d9472735ca4925bfc41e00897/src/JsonApiSerializer/JsonConverters/ResourceObjectConverter.cs#L262-L269

Whats the best starting point for this problem?
Should I implement an custom `ResourceObjectConverter` which is able to deal with the specific include option handling?

Thanks in advance!

**Comment by alex-davies** [comment]
You could write a custom ResourceObjectConvertor, but that is likely to be a lot of trouble.

I would probably try and modify the object you are serializing, so if you want to include the object then the your property would have the full object. If you don't want to include theobject then your property would just have an `id` and `type`

You might not do it exactly like this, but gives the idea
```csharp
        public class MinimalPerson
        {
            public string Id { get; set; }

            public string Type { get; set; } = "person";
        }

        public class Person : MinimalPerson
        {
            public string Name { get; set; }
        }

        public class Article
        {
            public MinimalPerson Author { get; set; }
        }


        var included = new Article
        {
            Author = new Person() { Id="arthurc" Name = "Arthur Collingdale"};
        }


        var notincluded = new Article
        {
            Author = new MinimalPerson() { Id = "arthurce" };
        }
```

I imagine you would also want your fetching logic to be different depending on if you are including or not, so it would not be too hard to return different objects for serialization.

**Comment by erikpaperik** [comment]
@codecutout thanks a lot for your hints!
