### ISSUE TITLE
Create Resource - Set Parent Id

### ISSUE THREAD

**Issue by btecu** [codecutout/JsonApiSerializer#57]
The JSON API standard for resource with parent relationship is as follows:
```
{
  "data": {
    "type": "photos",
    "attributes": {
      "title": "Ember Hamster",
      "src": "http://example.com/images/productivity.png"
    },
    "relationships": {
      "photographer": {
        "data": { "type": "people", "id": "9" }
      }
    }
  }
}
```
(http://jsonapi.org/format/#crud-creating)

Let's assume we have the following model in our code:
```
public class Photo {
        public int Id { get; set; }
        public int PeopleId { get; set; }
        public string Title { get; set; }
        public string Src { get; set; }
        public People People { get; set; }
    }
```

`PeopleId` is a EF specific way of creating the relationship easier. Right now the api will crash because EF is not able to save the data since the only field set on the People relationship is the Id. A workaround in the controller is:
```
photo.peopleId = photo.People.Id;
photo.people = null;
```
Is there a way we could get this work done automatically?

**Comment by alex-davies** [comment]
There is nothing out of the box that can help you map objects back to ID fields, although the solutions I can see for the problem would be
1. Separate your EF model from your contracts and handle the mapping yourself. Probably not as automatic as you wanted but it will prevent tight coupling your API contract to your database models and the mapping logic can be contained in an obvious mapping function
2. I'm not overly familiar with EF, but there should be a way to let it infer IDs from linked objects
3. You could extend your own `ResourceObjectConverter` (can pass into the constructor of `JsonApiSerializerSettings`), override the Read method then apply any additional mapping logic you want after calling the base functionality. Although this technically this would work, overall design-wise it may be hiding EF mapping concerns under the rug of deserialization. But this is an option available to you

**Comment by btecu** [comment]
It seems that the most correct solution would be `#1` - separating EF model vs client model.

For simple apps it might not be worth it as the models are very similar if not identical.

For the time being, I'll keep a single model with the mentioned above solution and if later the models diverge, I will split them and remove the workaround.

Thanks!
