### ISSUE TITLE
Double serialisation

### ISSUE THREAD

**Issue by PubuduGayan** [codecutout/JsonApiSerializer#6]
Correct me if I am wrong or I am using your library wrongly. When I try to serialise my DTO object it serialise two that make sense because in web api by default it will serialise json.net. but the thing is why I cant register JsonApiSerializerSettings as formatter in wep api config, then I believe this double serialisation will prevent.

any way this is awesome project. thanks for your sharing.

**Comment by alex-davies** [comment]
You can register a custom serialisation settings in web api by changing it in the webapi `HttpConfiguration` object

```
var config = new HttpConfiguration();
config.Formatters.JsonFormatter.SerializerSettings = new JsonApiSerializerSettings();
```

With that in place it will use json:api for all json responses.

**Comment by PubuduGayan** [comment]
Thanks
Alex will try and let you know.
Regards,
Pubudu

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by PubuduGayan** [comment]
this is working for ember , thanks.
