### ISSUE TITLE
Nested classes deserialization

### ISSUE THREAD

**Issue by jazpearson** [codecutout/JsonApiSerializer#60]
I have an issue where i'm trying to serialise an object, that has a top level class with an Id property, and a list of nested classes which also have an Id property.

```
    public class MyClass1
    {
        public string Id { get; set; }
        public string MyTopProperty { get; set; }

        public IEnumerable<MyClass2> MyClass2 { get; set; }
    }

    public class MyClass2
    {
        public string Id { get; set; }

        public string MyProperty { get; set; }
    }
```

and if i do:
```
            var myClass = new MyClass1()
                          {
                              MyTopProperty = "hello",
                              MyClass2 = new List<MyClass2>()
                                         {
                                         }
                          };

            var doc = new DocumentRoot<MyClass1>()
                      {
                          Data = myClass
                      };

            var json = JsonConvert.SerializeObject(doc, new JsonApiSerializerSettings());
```

this will give me:

```
{
  "data": {
    "type": "myclass1",
    "attributes": {
      "myTopProperty": "hello"
    },
    "relationships": {
      "myClass2": {
        "data": [
          
        ]
      }
    }
  }
}
```

when really i'm expecting to see:

```
{
  "data": {
    "type": "myclass1",
    "attributes": {
      "myTopProperty": "hello"
    },
    "relationships": {
      "myClass2": [    
        ]
    }
  }
}
```

this becomes an issue when i receive some json and i try deserialising it back into `MyClass1` and i get an exception that says  `Expected to find nested object within data.attributes.myClass2 that matches \data$\`

Is there a way around this?

**Comment by jazpearson** [comment]
I missed the part in the documentation about overriding `ResourceObjectConverter`

**Comment by alex-davies** [comment]
You shouldn't need to override `ResourceObjectConverter`. That is really only for advanced tweaking with the way the serialization works

The output you are getting is correct, its you expectation that is not right. Have a look at http://jsonapi.org/format/#document-resource-object-relationships the resource object should have a `data` element. That `data` element should contain an empty list if its a one-to-many relationship

**Comment by jazpearson** [comment]
Sorry. I wrote the wrong expectation out. It's been a long day.

```
{
  "data": {
    "type": "myclass1",
    "attributes": {
      "myTopProperty": "hello",
      "myClass2": [      
      ]
    }
  }
}
```

i was expecting `myClass2` to be an attribute of `MyClass1`, not a relationship.
