### ISSUE TITLE
Intercept "type" before deserializing

### ISSUE THREAD

**Issue by amit-ch** [codecutout/JsonApiSerializer#63]
Hi,
First off thanks for creating this library it works great!. 
Recently came across a requirement where a resource could be of any type and we need to deserialize into concrete type based on "type" property

For example we have sample json as
```{
  "data": {
    "type": "products",
    "id": "123456",
    "attributes": {},
    "relationships": {
      "content": {
        "links": {
          "self": "/v1/products/123456/relationships/content",
          "related": "/v1/products/123456/content"
        },
        "data": {
          "type": "contentA",
          "id": "999999"
        }
      }
    }
  }
}
```

content.data.type could be "contentA", "contentB" and so on.

And have defined below classes to deserialize into

```
using System.IO;
using System.Reflection;
using JsonApiSerializer;
using JsonApiSerializer.JsonApi;
using Newtonsoft.Json;

namespace MyJsonApiSerializer
{
    interface IContent
    {
        string Type { get; }
        string Id { get; }
    }

    class ContentA : IContent
    {
        public string Type { get; } = "contentA";
        public string Id { get; set; }
    }

    class ContentB : IContent
    {
        public string Type { get; } = "contentB";
        public string Id { get; set; }
    }

    class Product
    {
        public string Type { get; } = "products";
        public string Id { get; set; }

        [JsonProperty("content")] public Relationship<IContent> Content { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var thisAssembly = Assembly.GetExecutingAssembly();
            using (var stream = thisAssembly.GetManifestResourceStream("MyJsonApiSerializer.product.json"))
            {
                using (var reader = new StreamReader(stream))
                {
                    var json = reader.ReadToEnd();
                    var product = JsonConvert.DeserializeObject<Product>(json, new JsonApiSerializerSettings());
                }
            }
        }
    }
}
```
 
What we need is to deserialize the json into Product class but Content propery should get deserialized into Relationship<ContentA> or Relationship<ContentB> as per "type". Don't think JsonApiSerializer is smart enough to infer the type and deserialize accordingly but any help on how to extend the current behavior to support this would be appreciated.

**Comment by alex-davies** [comment]
@amit-ch Unfortunately this is not well supported at the moment. Your situation does already work for serialization unfortunately not for deserialization (which is a similar case if you were using regular json with Json.net). 

However, similar to json.net, you should be able create a custom `JsonConvertor` (you probably want to extend `ResourceObjectConvertor` to get the json:api handling) that makes some smart decisions about what type to deserialize as. Then you could apply it like

```csharp
[JsonProperty("content"), JsonConvertor(typeof(MyTypeSwitchConvertor))] public Relationship<IContent> Content { get; set; }
```

I can have a closer look at this over the next couple of days to try give you a working sample (and to make sure the library handles writing custom serializers in an intuitive way)

**Comment by alastairtree** [comment]
Would you take a PR on a small edits to ResourceObjectConvertor to expose the object creation to inheritors? Then you can just subclass and override and handle the object initialisation yourself, while maintaining the current default behaviour?

**Comment by alex-davies** [comment]
@alastairtree it sounds reasonable to separate out the object creation to a virtual method

Should probably also throw a meaningful error when we cant create an object (currently it seems to be throwing null reference)

Let me know if you need any help with the PR

**Comment by alex-davies** [comment]
Thanks for your help in implementing this. I have made a few tweaks to the PR and the feature has been added to 1.4.0

Feel free to reopen issue if you are having issues

**Comment by alastairtree** [comment]
Looks great, thank you.

**Comment by alastairtree** [comment]
Looks great, thank you.

**Comment by alastairtree** [comment]
Looks great, thank you.
