### ISSUE TITLE
Erro deserialize

### ISSUE THREAD

**Issue by diogotmlima** [codecutout/JsonApiSerializer#64]
error while trying to deserialize the following json
"{\"data\":[{\"type\":\"assets\",\"id\":7,\"attributes\":{\"asset_allocation_id\":6,\"asset_subtype_id\":14,\"code\":\"a18j09\",\"name\":\"a18j09\",\"active\":true,\"custom_asset_subtype\":false,\"custom_asset_allocation\":false,\"investment_variation\":\"ACV\",\"integer_min_investment\":false}}]}"
Error : Exception has occurred: CLR/JsonApiSerializer.Exceptions.JsonApiFormatException
An exception of type 'JsonApiSerializer.Exceptions.JsonApiFormatException' occurred in Newtonsoft.Json.dll but was not handled in user code: 'Expected to find json object at path '''
Model:
using System;
using System.ComponentModel.DataAnnotations;
using Newtonsoft.Json;
namespace App.ViewModel {
    public class assets {
        public int id { get; set; }
        public int asset_allocation_id { get; set; }
        public int asset_subtype_id { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public bool active { get; set; }
        public bool custom_asset_subtype { get; set; }
        public bool custom_asset_allocation { get; set; }
        public string isin { get; set; }
        public string trading_name { get; set; }
        public string description { get; set; }
        public string investment_variation { get; set; }
        public string custom_investment_variation { get; set; }
        public string issuer_name { get; set; }
        public byte? liquidity_days { get; set; }
        public decimal? min_investment { get; set; }
        public bool integer_min_investment { get; set; }
        public string indexer_name { get; set; }
        public asset_allocations asset_allocations { get; set; }
        public asset_subtypes asset_subtypes { get; set; }
    }
}

**Comment by alex-davies** [comment]
@diogothiago19  Your json:api document is a list of items so you need to deserialize it as a `asset[]`. I agree this error is not helpful and will try and make a change to make the error clearer.

You will also need to make id a `string` as well to make it conform to the json:api spec (and for the deserizlier to work)

**Comment by diogotmlima** [comment]
@codecutout  I made the changes suggested by you, but the error

public int id { get; set; }

  assets[] assetData = JsonConvert.DeserializeObject<assets[]> (assetDataJson, new JsonApiSerializerSettings ());

Exception has occurred: CLR/JsonApiSerializer.Exceptions.JsonApiFormatException
An exception of type 'JsonApiSerializer.Exceptions.JsonApiFormatException' occurred in Newtonsoft.Json.dll but was not handled in user code: 'Expected to find string at data[0].id. The value of 'id' MUST be a string'

**Comment by alex-davies** [comment]
@diogothiago19 The error is fairly self explanatory. Ids must be strings. 

This is a part of the jsonapi specification (http://jsonapi.org/format/#document-resource-object-identification). just change your id from `int` to `string`
