### ISSUE TITLE
Can we add errors to json incase of exceptions or validation failures 

### ISSUE THREAD

**Issue by ajaybommena** [codecutout/JsonApiSerializer#69]

**Comment by alex-davies** [comment]
Is there a specific case that you want to produce errors for?

There is some exceptions that are thrown for elements that directly contradict the specification as described at http://jsonapi.org/format/. This covers things like non-string ids or missing required elements. These exceptions are always of type `JsonApiFormatException` and if applicable will even have the specification text that is broken.

If you have a case that does not throw an exception and you think it should give me an example and I can look into it.

**Comment by alex-davies** [comment]
I'm closing the issues as im unsure what exceptions are expected to be thrown
