### ISSUE TITLE
Required fields on related objects failing model validation

### ISSUE THREAD

**Issue by Bouke** [codecutout/JsonApiSerializer#72]
First of all, thank you for this nice library! 👍 So far, implementing the server-side for an ember-data application I'm working on, has been great using this library. However I've started using model validation in combination with relationships, and now I'm running into the following issue.

Say I have a model like this (tree structure):
```c#
public class Category
{
    public string Id { get; set; }

    [Required]
    public string Name { get; set; }

    public Category Parent { get; set; }

    public IEnumerable<Category> Children { get; set; }
}
```

And I want to update an existing record:
```c#
[Route("{id}")]
public Category Patch(string id, [FromBody]Category category)
{
    category.Id = id;

    if (!ModelState.IsValid)
    {
        throw new HttpResponseException(Request.CreateErrorResponse(HttpStatusCode.BadRequest, ModelState));
    }

    // save in database & return
}
```

I want to be able to send the following JSON (generated by ember-data):
```json
{
    "data": {
        "attributes": {
            "name": "Apple TV"
        },
        "id": "5bb0bae631ee771950a56f27",
        "relationships": {
            "parent": {
                "data": {
                    "id": "5bb0b50f31ee752168a5b2b0",
                    "type": "categories"
                }
            }
        },
        "type": "categories"
    }
}
```

However, this JSON will fail ModelValidation for the relationship "parent":
```json
{
    "Message": "The request is invalid.",
    "ModelState": {
        "category.Parent.Name": [
            "The Name field is required."
        ]
    }
}
```

So my expectation is that while the "name" field is required, it shouldn't be required for referenced objects. For referenced objects, only "id" and "type" should suffice.

I've also seen [this comment](https://github.com/codecutout/JsonApiSerializer/issues/5#issuecomment-314844982) which might also work here. That would however require two models if I want to include full related objects for get queries and only light relationships for post/patch queries.

**Comment by alex-davies** [comment]
The deserializer will create a parent `Category` and try to populate it with all the data provided, in this case only `id` and `type`. Validation occurs *after* the deserialisation, so all the validation sees is a `Category` with only an `id` and a `null` name declaring it as invalid

If you are never expecting the user to update parent properties in that action you could make a new class 
```csharp
public class CategoryReference{
    public string Id { get; set; }
}
```

Then have 
```csharp
public class Category
{
    public string Id { get; set; }

    [Required]
    public string Name { get; set; }

    public CategoryReference Parent { get; set; }

    public IEnumerable<Category> Children { get; set; }
}
```

This would remove the parents `name` property so it doesn't validate but is making the assumption that you don't care about getting passed other parent properties



Another alternative would be to write custom validation, but I’m assuming that’s something you’re trying to avoid.

**Comment by Bouke** [comment]
Yeah that's also what I meant in the last paragraph of my addendum, to have an separate model that's used for create / update. However that requires me to create duplicate classes for all objects that I want to have the ability to provide related records for and have proper validation of those objects.

Custom validation is indeed not really what I'm looking for here, rather the ability to opt-out of certain validations, or the ability to be more explicit about what I want to validate. I understand that this serializer does not really have anything to do with validation, but I think the use-case is pretty common and I would be interested to see if we can come up with a better solution.

**Comment by Bouke** [comment]
I've implemented this with the code below; using an abstract base class that defines the shared properties, and two implementations one for outgoing instances, the other for incoming instances. I don't think this is a particular nice solution, but it gets the job done.

```c#
public abstract class CategoryBase
{
    public string Id { get; set; }

    public virtual string Name { get; set; }
}

public class Category : CategoryBase
{
    public Category Parent { get; set; }

    public IEnumerable<Category> Children { get; set; }
}

[MetadataType(typeof(CategoryMetadata))]
public class CategoryBody : CategoryBase
{
    public CategoryReference Parent { get; set; }

    public IEnumerable<CategoryReference> Children { get; set; }
}

public class CategoryMetadata
{
    [Required]
    public string Name { get; set; }
}

public class CategoryReference
{
    public string Id { get; set; }
}
```
