### ISSUE TITLE
Is there support for creating resources without client generated ID?

### ISSUE THREAD

**Issue by chrisketelaar** [codecutout/JsonApiSerializer#74]
Hi!

http://jsonapi.org/format/#crud-creating specifies that when creating a resource it should be possible to let the server create the ID. 

Can you tell me if this scenario is supported? And if yes could you point me in the right direction, I've been trying to get this working for a few hours how.

Thanks very much.

Regards,

Chris

**Comment by alex-davies** [comment]
It is supported in the sense the serializer will not throw an error if an `id` is absent in the request

Handling a null `id` and generating a new `id` is something your code will need to do
