### ISSUE TITLE
How to work with embedded objects?

### ISSUE THREAD

**Issue by Bouke** [codecutout/JsonApiSerializer#75]
From the JSON API specification on attributes:

> Attributes may contain any valid JSON value.

> Complex data structures involving JSON objects and arrays are allowed as attribute values. However, any object that constitutes or is contained in an attribute MUST NOT contain a relationships or links member, as those members are reserved by this specification for future use.

For example, I'd like to be able to (de)serialize the following JSON (especially the history bit):

```json
{
  "data": {
    "type": "user",
    "id": 5,
    "attributes": {
      "name": "David",
      "history": [
        { "url": "http://google.com", "time": "2015-10-01T20:12:53Z" },
        { "url": "http://apple.com",  "time": "2014-10-01T20:12:53Z" },
        { "url": "http://yahoo.com",  "time": "2013-10-01T20:12:53Z" }
      ]
    }
  }
}
```

[Some documentation from ember about embedded records](https://emberjs.com/api/ember-data/3.4/classes/DS.EmbeddedRecordsMixin).

Can this be done using this serializer already, or if not, what would be needed to achieve this?

**Comment by alex-davies** [comment]
This is already be handled by serializer. You just need to make sure your embedded objects don't contain an `id` field as then they will be treated as resource objects and generate them in the relationship section rather than the attribute section.

So your above example could be modelled with
```csharp
public class User
{
    public string Id { get; set; }

    public string Name { get; set; }

    public HistoryItem[] History {get; set; }
}

public class HistoryItem
{
    public string Url { get; set; }
    public DateTimeOffset Time { get; set; }
}
```

**Comment by Bouke** [comment]
That's great, will try out soon. Thank you!
