### ISSUE TITLE
Conditional Properties with JsonApiSerializer

### ISSUE THREAD

**Issue by samg-myob** [codecutout/JsonApiSerializer#89]
Hi,

In my API I want to be able dynamically serialize properties on my model. For example the user only requests certain fields - http://myurl.com?fields[myobject]=fieldA,fieldB,fieldC

I want to be able to read the _fields[myobject]_ property on my model and serialize only the properties that have been asked for by the user.

Hence in my controller I want to set the Conditional Properties on my model depending on fields user requests -
https://www.newtonsoft.com/json/help/html/ConditionalProperties.htm

Unfortunately this doesn't seem to apply/work with JsonApiSerializer.   As soon as the JsonApiSerializer is disabled ( and reverted to default Json.NET)  Conditional Properties work.

Any suggestions how to get Conditional Properties working with JsonApiSerializer ?

Thanks

**Comment by alex-davies** [comment]
I didn't even know that was an option the Json.Net, thanks for pointing it out. There is no explicit support for it within the JsonApiSerializer, but shouldn't be too hard to add support for it. How are you intending on using it, via the `ShouldSerializeX` or the custom `ContractResolver`? `ContractResolver` would require you to extend `JsonApiContractResolver` as that is how most of hte JsonApi magic is wired up.

As an aside this sort of logic would probably be cleaner and more obvious to sit in your controller logic, which would set the non-specified fields to `null` with `NullValueHandling = NullValueHandling.Ignore`.

**Comment by samg-myob** [comment]
Hi, thanks for your reply.

I am thinking of using it through `ShouldSerializeX`. That way we can deal with all the logic in our controllers - mapping the user specified fields to the fields that should/shouldn't be serialized. 

If there was support for this - that would be great. 

Unfortunately I think setting the non-specified fields to null with `NullValueHandling = NullValueHandling.Ignore` wont work for us. This is because we might have legitimate nullable fields. Especially when its a list of objects - it will be inconsistent to have some objects with fields present and some missing in the list.

**Comment by alex-davies** [comment]
Support for json.net conditional properties has now added in 1.6.2 (https://github.com/codecutout/JsonApiSerializer/pull/91)

let me know if you encounter any issues with it

**Comment by samg-myob** [comment]
Thank you
