### ISSUE TITLE
convert Type int to string

### ISSUE THREAD

**Issue by diogotmlima** [codecutout/JsonApiSerializer#90]
how to convert the id with integer type to string ?

**Comment by alex-davies** [comment]
Your `id` shouldnt be an integer, json:api specifies it should be a `string` (https://jsonapi.org/format/#document-resource-object-identification)

So you should define it in your model as a string

**Comment by jonnii** [comment]
@alex-davies it may be ergonomic to tostring whatever they have as an id... what do you think?

**Comment by alex-davies** [comment]
@diogotmlima, @jonnii you are not the only people this behaviour was tripping up, so I have conceded and integer ids are now allowed in 1.7.0 (https://github.com/codecutout/JsonApiSerializer/pull/98)

**Comment by jonnii** [comment]
I think this is the pragmatic choice, we make all our ids strings in the controller when we map to the wire types but this means we can remove the `ToString` calls we have there just to make JsonApiSerializer happy.
