### ISSUE TITLE
Cannot Serialize

### ISSUE THREAD

**Issue by stesvis** [codecutout/JsonApiSerializer#96]
I tried the serialization example and it works correctly like documented.
But when I try to serialize one of my objects I don't understand why it is not serialized with the JSON:API structure.

### Example

My class is:
```
public class VLSignUpRequestDTO
{
	[JsonProperty("email")]
	public string Email { get; set; }

	[JsonProperty("first-name")]
	public string FirstName { get; set; }

	[JsonProperty("last-name")]
	public string LastName { get; set; }

	[JsonProperty("password")]
	public string Password { get; set; }

	[JsonProperty("password-confirmation")]
	[JsonIgnore]
	public string ConfirmPassword { get; set; }

	[JsonProperty("referral-code")]
	public string ReferralCode { get; set; }

	[JsonProperty("accept_terms")]
	public bool AreTermsAccepted { get; set; }

	[JsonProperty("shop")]
	public bool? Shop { get; set; }

	[JsonProperty("company-name")]
	public string CompanyName { get; set; }
}
```

Then I try to serialize it like this:
```
var signUp = new VLSignUpRequestDTO
{
	AreTermsAccepted = true,
	CompanyName = "My Company",
	Email = "test@mycompany.com",
	FirstName = "John",
	LastName = "Doe",
	Password = "qwerty"
};

string json = JsonConvert.SerializeObject(signUp, new JsonApiSerializerSettings());
```
And the json result string is this:
```
[
  {
    "email": "test@mycompany.com",
    "first-name": "John",
    "last-name": "Doe",
    "password": "qwerty",
    "accept_terms": true,
    "company-name": "My Company"
  }
]
```

How can I get it to format as
```
{
  "data": {
    "type": "VLSignUpRequestDTO",
    "attributes": {
      "email": "test@mycompany.com",
      "first-name": "John",
      "last-name": "Doe",
      "password": "qwerty",
      "shop": false,
      "company-name": "My Company",
      "referral-code": ""
    }
  }
}
```
etc?

**Comment by alex-davies** [comment]
By default the serializer uses the presence of an Id field to determine if the object is a resource object. Resource objects should contain an Id anyway, I believe spec says the only time they might not have an Id is within a request to create a new object, where the server is left to do the Id generation

so easiest fix is to just add a `public string Id { get; set; }` to your object

**Comment by stesvis** [comment]
> By default the serializer uses the presence of an Id field to determine if the object is a resource object. Resource objects should contain an Id anyway, I believe spec says the only time they might not have an Id is within a request to create a new object, where the server is left to do the Id generation
> 
> so easiest fix is to just add a `public string Id { get; set; }` to your object

Correct, that was the missing piece. Thanks!
